author: SpleefLeague
authors: [ NickM13 ]
description: SpleefLeague Core Plugin
main: com.spleefleague.core.Core
name: Core
url: http://www.spleefleague.com/
version: 1.1
api-version: 1.19
softdepend: [ ProtocolLib ]
loadbefore: [ CoreZones, Spleef, Splegg, SuperJump ]